### Listar usuarios
GET http://{{host}}/api/{{version}}/users
Authorization: Bearer {{auth_token}}

> {%
    client.test("Petición exitosa y datos obtenidos", function () {
        client.assert(response.status===200, "Status obtenido: " + response.status);
        client.assert(response.body && response.body.length>0, "Petición exitosa, pero lista vacía");
    })

    if (response.status===200 && response.body.length>0) {
        client.global.set("user_id", response.body[0].id);
        client.log("Petición exitosa, ID obtenido: " + response.body[0].id);
    }
%}

### Obtener por ID
GET http://{{host}}/api/{{version}}/users/{{user_id}}
Authorization: Bearer {{auth_token}}

> {%
    client.test("Petición exitosa", function () {
        client.assert(response.status===200, "Status obtenido: " + response.status);
        client.assert(response.body.id===client.global.get("user_id"), "El id no coincide con el recibido");
    })
%}

### Eliminar por ID
DELETE http://{{host}}/api/{{version}}/users/{{user_id}}
Authorization: Bearer {{auth_token}}

> {%
    client.test("Petición exitosa", function () {
        client.assert(response.status===204, "Status obtenido: " + response.status);
    })
%}

### Crear usuario (ADMIN)
POST http://{{host}}/api/{{version}}/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "RafaelC",
  "email": "rcastillo@example.com",
  "password": "rafatillo123",
  "firstName": "Rafael",
  "lastName": "Castillo",
  "role": "ADMIN"
}

> {%
    client.test("Petición exitosa", function () {
        client.assert(response.status===201, "Status obtenido: " + response.status);
        client.assert(response.body.id != null);
    })
%}